### ISSUE TITLE
Improvents ideas

### ISSUE THREAD

**Issue by panzli** [TLINDEN/kleingebaeck#30]
Firstly I would say thanks for your cool project.

I have a few ideas, which could improve this projects for me (and others ?).

Last week i tried to build a docker container with the main branch and it was always failing with an error by compiling the package.

Now my question:  Is the main  branch a stable branch?

Today I've tried it again and now it works.

```
From golang:1.21.5
WORKDIR /root/
RUN apt update -y
RUN apt-get install -y git make
RUN git clone https://github.com/TLINDEN/kleingebaeck --branch main
#RUN git clone https://github.com/TLINDEN/kleingebaeck --branch v0.1.0 # fix for last week
WORKDIR	 /root/kleingebaeck
RUN make
RUN make install
```
```
version: "3.9"
services:

  kleinanzeigen-backup:
    container_name: kleinanzeigen-backup
    volumes:
      - ./config:/config
      - /mnt/ubuntu-nfs/backup/kleinanzeigen:/backup
    command: /bin/bash -c '
      kleingebaeck -u x -d && echo "success ad"  ; # telegram?
      kleingebaeck -u x -d && echo "success wd" ;
      kleingebaeck -u x -d && echo "success jb" '

    working_dir: /backup
    image: kleingebaeck:latest
    build: .
```

2. In the new version v0.1.1 the ads are saved with the id. 

Unfortunately this isn't working in my environment, because I use "hochschieben" and  the add gets a new ID and I get duplicates.
I already have read you *limitations* , but could you please add a tag to exclude the id in the backup folder for the ad?

3. Because I'm using "hochschieben" on the other way, I have sometime corrupted pictures, which doesn't are downloadable and provide a 200 success code.
If the scraper get such a picture, it fails with the following error:

`folgt`

Unfortunately I could't find any skip error options, could you please ad another flag for this?
